TARGET ?= iphone:clang:14.5:10.0
ARCHS ?= arm64 armv7
DEBUG ?= no

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = WeChatCallkitEnabler
WeChatCallkitEnabler_FILES = Tweak.x

include $(THEOS_MAKE_PATH)/tweak.mk